### ISSUE TITLE
Define and document core architecture

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen#1]
This project is going to be in node, but we have not nailed down much beyond that.  There is a lot to the vision (a draft image of the vision included here) but we should formally document that somewhere and that will enable us to make more code-centric issues in this (or maybe additional) repositories.

For example; how will processing modules be managed (will they be baked into this repository or will there be some kind of package management), what is part of the "core" and what is optional, will there be any centralized / coordinating component, etc etc.

I may update this issue to reflect some of those questions, or I may treat that as part of the issue's task itself.

**Comment by slifty** [comment]
Here is an *in progress* diagram; any thoughts / feedback / questions welcome

<img width="836" alt="image" src="https://user-images.githubusercontent.com/208884/75725640-e25c8300-5cae-11ea-9092-33f94c27fce2.png">

**Comment by slifty** [comment]
I was given feedback that none of this makes a lick of sense.  Part of the issue is I'm trying to diagram 5 different components at once.  I'm going to try starting with the high level and then make diagrams for the inside of the TV kitchen.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/208884/75734516-2444f380-5cc6-11ea-8913-38d8aaaffdc2.png">

**Comment by slifty** [comment]
Here is an attempt at the TV kitchen itself
<img width="763" alt="image" src="https://user-images.githubusercontent.com/208884/75736570-8eac6280-5ccb-11ea-9d31-87c39c876bf6.png">

**Comment by reefdog** [comment]
The new breakdown is _so much more_ coherent, thank you! (With the exception that "ingredients" as the local cache isn't quite right… I think that should be "cutting board" perhaps? Or "mixing bowl"? We are toeing the line of unacceptable adherence to the metaphor here tho…)

**Comment by slifty** [comment]
To be clear: the data are the ingredients, the cache itself was not given a name (though I would call it the refrigerator, personally)

**Comment by reefdog** [comment]
Ahhh I see.

**Comment by slifty** [comment]
Question answering:

> Will the configuration API really talk directly to the external storage coordinator? Or will the external storage coordinator draw its configuration from the configuration store? (I feel like the latter/second/last-thing-I-said is more correct.)

Good catch; that arrow should be from the configuration store

> Can you rename "External data coordinator" to something more like "Input coordinator"? As-is it's confusing b'c of the external storage/archive piece.

Yes

> Will the line cooks get their instrux from the Sous Chef directly, or the Kafka queue? I would assume the latter/second/last-thing-I-said? (This is mostly a question about the arrows connecting those pieces.)

Line cooks wouldn't talk to kafka -- they don't know the big picture, or what kafka messages should trigger what actions.  In that sense the sous chef is the sole monitor / watcher of the kafka queue and would spin up "line cooks" to do specific tasks, providing the data (ingredients) and information about which appliance to use, based on what the pipeline path ("recipe") called for.

Phewf what a great meatphore.

**Comment by slifty** [comment]
testing

**Comment by slifty** [comment]
Question answering:

> Will the configuration API really talk directly to the external storage coordinator? Or will the external storage coordinator draw its configuration from the configuration store? (I feel like the latter/second/last-thing-I-said is more correct.)

Good catch; that arrow should be from the configuration store

> Can you rename "External data coordinator" to something more like "Input coordinator"? As-is it's confusing b'c of the external storage/archive piece.

Yes

> Will the line cooks get their instrux from the Sous Chef directly, or the Kafka queue? I would assume the latter/second/last-thing-I-said? (This is mostly a question about the arrows connecting those pieces.)

Line cooks wouldn't talk to kafka -- they don't know the big picture, or what kafka messages should trigger what actions.  In that sense the sous chef is the sole monitor / watcher of the kafka queue and would spin up "line cooks" to do specific tasks, providing the data (ingredients) and information about which appliance to use, based on what the pipeline path ("recipe") called for.

Phewf what a great meatphore.

**Comment by reefdog** [comment]
Thanks! And yes as you well know, I don't have any idea how queues work and steadfastly refuse to learn.

**Comment by slifty** [comment]
Your idea may end up being useful too!

I was thinking of kafka as JUST a messaging queue (to announce when things get finished ), but if we also used it for a job queue (to say "hey this needs to get done next) then you may well be right that we should also have the line cooks listening directly.

**Comment by slifty** [comment]
Speaking of updates: 
<img width="763" alt="image" src="https://user-images.githubusercontent.com/208884/75820884-32991b00-5d6b-11ea-9aba-a1ff0cdf4e65.png">

**Comment by reefdog** [comment]
> if we also used it for a job queue (to say "hey this needs to get done next) then you may well be right

That's what I meant, then.
