### ISSUE TITLE
ffmpeg / stream exploration

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen#14]
## Discussion

**What do you want to talk about?**

As we begin to work on the input coordinator / ingestion engines, we discussed that the primary purpose of these modules will be to convert the input into a standardized video stream type.

The question is what should that stream type be.  We should also think through what the likely input formats will be (file, youtube, youtube live, HD HomeRun)

**Relevant resources**

1. We have some access to folks who have worked a lot in this space, so lets tap into their recommendations.  @traceypooh in particular!
2. The [developer documentation of HDHomeRun](https://www.silicondust.com/hdhomerun/hdhomerun_development.pdf)
3. [ffmpeg formats](https://ffmpeg.org/ffmpeg-formats.html)
4. [ffmpeg streaming guide](https://trac.ffmpeg.org/wiki/StreamingGuide)

**Comment by reefdog** [comment]
A few thoughts about standardizing the stream.

1. The easiest ingestion processing is no processing, so wherever possible, **configure the source input delivery format to match our standardized output preferences.** Meaning, if we decide to deal exclusively with h264 inside the kitchen, request content in h264 from our input streams (HDHomeRun, YouTube) so the ingestion engine doesn't have to convert. Similarly, if we want to deal internally with no more than 1080p video, request 1080p video sources so we're downscaling as rarely as possible.
2. **Minimize the number of format options we choose to standardize.** Do we need to standardize the frame rate, or can we commit to dealing internally with the native one? I can imagine setting a cap (like 30fps) beyond which we don't gain value, but below that cap, if we can pass through 24 or 25 or 29.97 or 30 unmodified, we again reduce our processing requirements.

_Sending this comment mid-flight even though I can/need to add more detail!_

**Comment by slifty** [comment]
I think we can close this at this point!

We locked in on MPEG-TS as a container format, we also have a pretty robust ffmpeg stream pipeline about to be merged in as part of the work on #45.

I'm sure some day we'll want to do more exploration about optimizing encoding formats or some such thing, but for now I don't think we have active open questions.
