### ISSUE TITLE
Create a better set of issue labels

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen#2]
Lets have issue labels that are thoughtful and apply to this project.

**Comment by reefdog** [comment]
I tried to start improving them, then discovered whatever type of user I am here, I can't create or edit labels. 😞

**Comment by slifty** [comment]
It would be good to list them here first anyway just for the heck of it!  But I'll upgrade you to a Premium "BIFFUD" Account

**Comment by reefdog** [comment]
I accidentally opened the notification link to that comment in the wrong browser, where I'm not signed in to GitHub, and briefly thought you'd _downgraded_ me somehow, and honestly was 100% not surprised.

**Comment by slifty** [comment]
I did this all by myself, no thanks to anybody else

**Comment by slifty** [comment]
(Justin helped)
