### ISSUE TITLE
tv-kitchen?

### ISSUE THREAD

**Issue by Laurian** [tvkitchen/tv-kitchen#27]
#### What do you want to talk about?
what does `tv-kitchen` stand for? since `tv` is an abbreviation what is `kitchen`? abbreviation of what? an acronym `k.i.t.c.h.e.n`?

#### Relevant Resources / Research
[Kitchen (TV series)](https://en.wikipedia.org/wiki/Kitchen_(TV_series)) (Russian: Кухня, Kukhnya Serbian: Кухиња, Kuhinja) is a Russian comedy series that airs on STS. The show focuses on the comedic events that unfold in a fictional restaurant in Moscow called "Claude Monet".

**Comment by slifty** [comment]
This is a critical question and may take some time to fully think through.

**Comment by reefdog** [comment]
`[T][V] [K]itchen [I]ngests [T]elevision/[C]able/[H]TTP/[E]tc. [N]etworks`

**Comment by slifty** [comment]
Here's what I have so far

```
[T]
[V]

[K]itchen
[I]n
[T]he
[C]
[H]ooooooooooouse!!!
[E]
[N]
```

**Comment by reefdog** [comment]
TV KITMFHEN

**Comment by markstencel** [comment]
TV Kit for Channeling Electronic News (TV KitCHEN)

**Comment by mhirsch** [comment]
```
[T] ele
[V] ision

[K]itchen
[I]n
[T]he
[C]
[H]ooooooooooouse!!!
[E]
[N]
```

**Comment by slifty** [comment]
I think it's safe to say that we've explored this as deeply as possible.
