### ISSUE TITLE
Sort out our Travis integration

### ISSUE THREAD

**Issue by reefdog** [tvkitchen/tv-kitchen#48]
#### What do you want to talk about?

1. The `tvkitchen` GitHub organization is [configured to provide third-party access](https://github.com/organizations/tvkitchen/settings/oauth_application_policy) with both travis-ci.org (Travis for open source projects) and travis-ci.com (commercial Travis). **First question: why both? Can we integrate with only .org for simplicity?**
2. Perhaps as an extension as above, we also have the [Travis CI GitHub App](https://github.com/organizations/tvkitchen/settings/installations) configured at the organization setting. I can't tell if this is for both .org and .com integrations, or just one?
3. This repo has its own [webhook integration with travis-ci.org](https://github.com/tvkitchen/tv-kitchen/settings/hooks), which explains why every PR spawns four Travis builds (two for travis-ci.com and two for travis-ci.org). **We should remove this, probably.**

So, the basic discussion/task here:

1. What needs changing?
2. Let's change it!

**Comment by reefdog** [comment]
I _think_ all we really need to do is remove the webhook from this repo and rely on the org-level Travis CI integration definition with travis-ci.com. Whatever distinction there is between .com and .org is nullified by .com offering free integration for open-source projects anyway?

**Comment by slifty** [comment]
I just removed the webhook; I think we'll know if it worked next time we open a PR?

**Comment by slifty** [comment]
I believe this is now working as expected.
