### ISSUE TITLE
Let's talk configuration!

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen#64]
#### What do you want to talk about?
The long term vision for configuration would allow for things like API and UX based configuration.

The short term vision for configuration is necessarily far simpler.  This issue is about the short term.

This issue is about fleshing out the contents of a `config.json` which will allow someone to set up:

* Ingestion streams
* A topology of appliances

This list may well expand.

#### Relevant Resources / Research
None

**Comment by slifty** [comment]
How's this for a proposed format:

*config.json*
```json
{
  "sources": [
    {
      "type": "",
      "ingestionEngine": "",
      "metadata": {},
    }
  ]
  "appliances": [
    {
      "package": "",
      "settings": {},
    }
  ]
}
```

This plan would have some secondary impacts:

* We might want to create the concept of ingestion engine names (or maybe we would want to just use the class name of the ingestion engine?)
* We should consider fleshing out the `metadata` associated with a stream (for now we can just skip that field / not formalize it yet -- we don't have to block on this)

Appliance settings would be up to the individual appliance to specify; the field would just be a key / value store that is passed to the appliance's constructor in the `settings` parameter.

**Comment by reefdog** [comment]
> Appliance settings would be up to the individual appliance to specify; the field would just be a key / value store that is passed to the appliance's constructor in the settings parameter.

Strikes me that verifying the format/contents of these settings is another thing the appliance's `doctor` should do.

**Comment by slifty** [comment]
> Strikes me that verifying the format/contents of these settings is another thing the appliance's doctor should do.

Doctor would be run outside of the context of configuration of an appliance, so I'm not sure that's true.

e.g. doctor would be run to just say "are all the appliance pre-requisites installed?"

I'm not sure settings need a validation method -- if the config is invalid it will either not work as expected OR it will fail to construct because a required setting was not provided.  Do other projects with dynamic setting objects have a validation mechanism?  I guess travis has `travis lint` for instance.  (either way I think that would be a separate thing, not a doctor thing)

**Comment by slifty** [comment]
We have moved down a path of using the countertop API to add appliances (see #82)

In particular, configuration is going to happen in TVK instances -- where the countertop is imported as a package (package TBD #80) and coded against, as opposed to configuration happening directly on a *clone* of this repository.
